# Aersopace configuration file for window manager similar to i3.

# Available commands: https://nikitabobko.github.io/AeroSpace/commands

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 40

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false
# Disable annoying and useless "hide application" shortcut
# cmd-h = [] # Disable "hide application"
# cmd-alt-h = [] # Disable "hide others"

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[key-mapping]
preset = 'qwerty'

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
################################################################################
# FOCUS, not necessary now that I'm using 
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-j = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-k = 'focus down'
# cmd-l = 'focus up'
cmd-semicolon = 'focus right --boundaries-action wrap-around-the-workspace'
shift-cmd-tab = 'focus right --boundaries-action wrap-around-the-workspace'
ctrl-shift-cmd-c = 'focus right --boundaries-action wrap-around-the-workspace'

## On I3, I usually use other monitor for workspaces 6 and 7. since aerospace works a little differently, I'll have 6 and 7 switch between the two workspaces. I only really need 5 or 6 workspaces on mac.
shift-cmd-j = 'focus-monitor prev' 
shift-cmd-semicolon = 'focus-monitor next' 

shift-cmd-l= "move-node-to-monitor next"
shift-cmd-k= "move-node-to-monitor prev"
################################################################################
# LAYOUTS
# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-h = 'layout tiles horizontal'
cmd-g = 'layout accordion horizontal'

################################################################################
# WORKSPACES
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1' # teams
cmd-2 = 'workspace 2' # chat(slack/discord/etc)
cmd-3 = 'workspace 3' # browser(work)
cmd-4 = 'workspace 4' # db tool
cmd-5 = 'workspace 5' # postman
cmd-6 = 'workspace 6' # fun
cmd-7 = 'workspace 7' # fun
cmd-8 = 'workspace 8' # misc(finder/vpn/docker)
cmd-9 = 'workspace 9' # misc(finder/vpn/docker)

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-cmd-1 = 'move-node-to-workspace 1'
shift-cmd-2 = 'move-node-to-workspace 2'
shift-cmd-3 = 'move-node-to-workspace 3'
shift-cmd-4 = 'move-node-to-workspace 4'
shift-cmd-5 = 'move-node-to-workspace 5'
shift-cmd-6 = 'move-node-to-workspace 6'
shift-cmd-7 = 'move-node-to-workspace 7'
shift-cmd-8 = 'move-node-to-workspace 8'
shift-cmd-9 = 'move-node-to-workspace 9'


#NOTE: to find bundle id of app: osascript -e 'id of app "kitty"'           
# [[on-window-detected]]
#     if.app-id = 'com.todesktop.230313mzl4w4u92' #Cursor
#     run = 'move-node-to-workspace 1'

[[on-window-detected]]
    if.app-id = 'net.kovidgoyal.kitty'
    run = 'move-node-to-workspace 1'

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = 'move-node-to-workspace 2'

[[on-window-detected]]
    if.app-id = 'com.google.android.studio' 
    run = 'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id = 'com.apple.dt.Xcode' 
    run = 'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id = 'org.jkiss.dbeaver.core.product'
    run = 'move-node-to-workspace 5'

[[on-window-detected]]
    if.app-id = 'com.postmanlabs.mac' 
    run = 'move-node-to-workspace 5'

#Notes
[[on-window-detected]]
    if.app-id = 'md.obsidian' 
    run = 'move-node-to-workspace 6'

#Communication
[[on-window-detected]]
    if.app-id = 'com.microsoft.teams2'
    run = 'move-node-to-workspace 7'



[workspace-to-monitor-force-assignment]
    1 = 'main'                           # Monitor sequence number from left to right. 1-based indexing
    2 = 'main'                       # Main monitor
    3 = 'main'                  
    4 = 'main'                  
    5 = 'main'                  
    6 = 'secondary'
    7 = 'secondary'
    8 = 'secondary'
    # 3 = 1                  # Non-main monitor in case when there are only two monitors
    # 4 = 'built-in'                   # Case insensitive regex substring
    # 5 = '^built-in retina display$'  # Case insensitive regex match
    # 6 = ['secondary', 'dell']        # You can specify multiple patterns.
                                     #   The first matching pattern will be used
