# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 40

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10
# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-j = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-k = 'focus down'
# cmd-l = 'focus up'
cmd-semicolon = 'focus right --boundaries-action wrap-around-the-workspace'
shift-cmd-tab = 'focus right --boundaries-action wrap-around-the-workspace'
ctrl-shift-cmd-c = 'focus right --boundaries-action wrap-around-the-workspace'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-h = 'layout tiles horizontal'
cmd-g = 'layout accordion horizontal'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# Current work setup with each app I keep in each workspace
# This way I always have 1 keypress to get to my most used apps
# On my personal PopOs laptop, I have the same workspaces but dont use most
cmd-1 = 'workspace 1' # terminal
cmd-2 = 'workspace 2' # browser(work)
cmd-3 = 'workspace 3' # chat(slack/discord/etc)
cmd-4 = 'workspace 4' # postman
cmd-5 = 'workspace 5' # db tool
cmd-6 = 'workspace 6' # db tool
cmd-7 = 'workspace 7' # db tool
cmd-8 = 'workspace 8' # misc(finder/vpn/docker)
cmd-9 = 'workspace 9' # misc(finder/vpn/docker)

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-cmd-1 = 'move-node-to-workspace 1'
shift-cmd-2 = 'move-node-to-workspace 2'
shift-cmd-3 = 'move-node-to-workspace 3'
shift-cmd-4 = 'move-node-to-workspace 4'
shift-cmd-5 = 'move-node-to-workspace 5'
shift-cmd-6 = 'move-node-to-workspace 6'
shift-cmd-7 = 'move-node-to-workspace 7'
shift-cmd-8 = 'move-node-to-workspace 8'
shift-cmd-9 = 'move-node-to-workspace 9'

## On I3, I usually use other monitor for workspaces 6 and 7. since aerospace works a little differently, I'll have 6 and 7 switch between the two workspaces. I only really need 5 or 6 workspaces on mac.
shift-cmd-j = 'focus-monitor prev' 
shift-cmd-semicolon = 'focus-monitor next' 

shift-cmd-k= "move-node-to-monitor next"
shift-cmd-l= "move-node-to-monitor prev"

# Disable annoying and useless "hide application" shortcut
# cmd-h = [] # Disable "hide application"
# cmd-alt-h = [] # Disable "hide others"
