#!/usr/bin/env bash
# regen-anchor.sh — regenerate ONLY the <!-- AUTO:START -->…<!-- AUTO:END --> block of a
# project anchor at ~/.agent/anchors/{project}.md from the filesystem. Hand-curated
# sections above the marker are never touched. Scaffolds a fresh anchor if none exists.
#
#   regen-anchor.sh [project]      # project defaults to name resolved from $PWD
#
# Deterministic + idempotent: same inputs → same AUTO block. No network.
set -euo pipefail

HOOKS_DIR="$HOME/.dotfiles/.config/shared-hooks"
MAP_FILE="$HOOKS_DIR/project-map.json"

# --- resolve project name ---
if [ "${1:-}" != "" ]; then
  PROJECT="$1"
else
  # shellcheck disable=SC1091
  . "$HOOKS_DIR/project-name.sh"
  PROJECT="$(resolve_project_name "${CLAUDE_PROJECT_DIR:-$PWD}")"
fi

ANCHOR_DIR="$HOME/.agent/anchors"
ANCHOR="$ANCHOR_DIR/$PROJECT.md"
PLAN_DIR="$HOME/.agent/plans/$PROJECT"
LESSONS="$HOME/.agent/lessons/$PROJECT.md"
EVAL_DIR="$HOME/.agent/evals/$PROJECT"
mkdir -p "$ANCHOR_DIR"

START='<!-- AUTO:START — regenerated by /project-index; edits below are overwritten -->'
END='<!-- AUTO:END -->'

# --- gather facts ---
# repo path: reverse-lookup in project-map.json paths
REPO=""
if command -v jq >/dev/null 2>&1 && [ -f "$MAP_FILE" ]; then
  REPO=$(jq -r --arg n "$PROJECT" '.paths | to_entries[] | select(.value==$n) | .key' "$MAP_FILE" 2>/dev/null | head -1)
fi
# tracker line
TRACKER=""
if command -v jq >/dev/null 2>&1 && [ -f "$MAP_FILE" ]; then
  TRACKER=$(jq -r --arg n "$PROJECT" '(.trackers[$n] // .trackers.default) | "\(.system) — \(.instance)"' "$MAP_FILE" 2>/dev/null)
fi
# latest eval
LATEST_EVAL=$(ls -t "$EVAL_DIR" 2>/dev/null | head -1 || true)
# lab ideation dir (best-effort: same name under lab/projects/current)
LAB_DIR=""
for cand in "$PROJECT" "${PROJECT%-agent}" "${PROJECT%-platform}"; do
  if [ -d "$HOME/.notes/lab/projects/current/$cand" ]; then
    LAB_DIR="~/.notes/lab/projects/current/$cand/"; break
  fi
done
[ -z "$LAB_DIR" ] && LAB_DIR="~/.notes/lab/ (no dedicated projects/current entry)"
# repo docs
REPO_DOCS="_(none)_"
[ -n "$REPO" ] && [ -d "$REPO/docs" ] && REPO_DOCS="$REPO/docs/"

# --- build the AUTO block ---
auto_block() {
  echo "$START"
  echo "## Links"
  echo "- Plans:   \`~/.agent/plans/$PROJECT/\`"
  echo "- Lessons: \`~/.agent/lessons/$PROJECT.md\`"
  if [ -n "$LATEST_EVAL" ]; then
    echo "- Evals:   \`~/.agent/evals/$PROJECT/\` (latest: \`$LATEST_EVAL\`)"
  else
    echo "- Evals:   \`~/.agent/evals/$PROJECT/\`"
  fi
  echo "- Ideation/docs: \`$LAB_DIR\`"
  echo "- Repo docs: $REPO_DOCS"
  [ -n "$REPO" ] && echo "- Repo: \`$REPO\`"
  [ -n "$TRACKER" ] && echo "- Tracker: $TRACKER"
  echo
  echo "## Active plans (most recent)"
  if [ -d "$PLAN_DIR" ]; then
    local plans
    plans=$(ls -t "$PLAN_DIR" 2>/dev/null | grep -vxE 'active|archive|_archive|tasks' | head -5 || true)
    if [ -n "$plans" ]; then
      echo "$plans" | sed 's/^/- `/; s/$/`/'
    else
      echo "- _(no plans yet)_"
    fi
  else
    echo "- _(no plans dir yet)_"
  fi
  echo
  echo "## Recent lessons (digest)"
  if [ -f "$LESSONS" ]; then
    local digest
    # tail of bullet lessons, each truncated to keep the digest scannable (it's injected
    # at session start — one mega-lesson must not dominate the context window)
    digest=$(grep -E '^- ' "$LESSONS" 2>/dev/null | tail -5 \
      | awk '{ if (length($0) > 200) print substr($0,1,197) "…"; else print }' || true)
    if [ -n "$digest" ]; then
      echo "$digest"
    else
      echo "- _(lessons file has no bullet entries yet)_"
    fi
  else
    echo "- _(no lessons file yet)_"
  fi
  echo "$END"
}

# --- scaffold if missing ---
if [ ! -f "$ANCHOR" ]; then
  {
    echo "# $PROJECT — anchor"
    echo
    echo "## Key URLs & facts"
    [ -n "$REPO" ] && echo "- **Repo:** \`$REPO\`"
    [ -n "$TRACKER" ] && echo "- **Tracker:** $TRACKER"
    echo "- _(fill in: main branch, deploy target, key paths)_"
    echo
    echo "## Decisions log"
    echo "- _(record decisions + WHY as they land — the irreplaceable part)_"
    echo
    echo "## Blockers / known issues"
    echo "- _(none yet)_"
    echo
    auto_block
  } > "$ANCHOR"
  echo "scaffolded new anchor: $ANCHOR"
  exit 0
fi

# --- replace only the AUTO block in the existing file ---
if ! grep -qF 'AUTO:START' "$ANCHOR"; then
  echo "ERROR: $ANCHOR has no AUTO:START marker — append one or delete the file to re-scaffold." >&2
  exit 1
fi

TMP="$(mktemp)"
# keep everything before the START marker line, inject fresh block, keep from END marker on
awk -v startpat='AUTO:START' -v endpat='AUTO:END' '
  index($0, startpat) { print "@@AUTO@@"; skip=1; next }
  index($0, endpat)   { skip=0; next }
  skip { next }
  { print }
' "$ANCHOR" > "$TMP.body"

# splice generated block in place of the @@AUTO@@ sentinel
{
  while IFS= read -r line; do
    if [ "$line" = "@@AUTO@@" ]; then
      auto_block
    else
      printf '%s\n' "$line"
    fi
  done < "$TMP.body"
} > "$TMP"

mv "$TMP" "$ANCHOR"
rm -f "$TMP.body"
echo "regenerated AUTO block: $ANCHOR"
