//! `notes board` — every project's current wave, human and `#ai` lanes, in one file.
//!
//! WHY THIS IS A FILE AND NOT A SECTION
//!
//! The daily note is the human's FOCUS surface. Rendering the board into it was the
//! obvious move and is the wrong one: the note is what gets opened in nvim every morning,
//! and anything pasted above `## Focus` competes with the one list the human actually
//! maintains. `## Current Projects` already proved that — a static index copy that earned
//! its removal. So the board is a file the footer LINKS: visible in one click, never in
//! the way.
//!
//! WHY IT CANNOT DISAGREE WITH THE COCKPIT
//!
//! It reads each project's `## Wave` through `project_tasks::open_wave_for_dir` — the same
//! sheet, the same heading resolution and the same open-task predicate that `notes ptask
//! list` and `notes-cockpit.sh` use. There is one list, rendered twice, rather than two
//! lists that drift. `#ai` is the lane marker throughout (a `/wave` dispatches exactly the
//! `#ai` items), so the board shows the split rather than inventing a vocabulary.
//!
//! CROSS-PROFILE ON PURPOSE
//!
//! Every profile's projects land in one file. "I don't know where <that app> is" was a
//! real complaint: per-profile surfaces mean the work you are not currently looking at is
//! invisible, which is the failure mode a board exists to prevent.

use crate::config::{self, Profile};
use crate::daily;
use crate::logging::Logger;
use crate::md;
use crate::project_tasks;
use anyhow::{Context, Result};
use chrono::Local;
use std::fs;
use std::path::PathBuf;

/// Where the board is written for a profile: alongside the project index it complements
/// (`lab/projects/board.md`). `None` when the profile configures no projects dir, which is
/// also what makes this a no-op on a profile that has no lab.
pub fn board_path(p: &Profile) -> Option<PathBuf> {
    p.project_index
        .as_ref()
        .and_then(|idx| idx.parent())
        .map(|dir| dir.join("board.md"))
}

/// One project's rendered block, or `None` when it has no task sheet.
fn project_block(name: &str, dir: &std::path::Path) -> Option<String> {
    let (version, open) = project_tasks::open_wave_for_dir(dir)?;
    let ai = open.iter().filter(|l| is_ai(l)).count();

    let mut s = format!("## {name} · {version} — {} open", open.len());
    if ai > 0 {
        s.push_str(&format!(" ({ai} @ai)"));
    }
    s.push('\n');
    if open.is_empty() {
        // An empty board is a fact worth rendering. Omitting the project entirely would
        // read as "not set up" rather than "nothing queued".
        s.push_str("_(nothing queued)_\n");
        return Some(s);
    }
    // `#ai` first: the agent lane is the half the human is not holding in their head.
    let (ai_lines, mine): (Vec<_>, Vec<_>) = open.iter().partition(|l| is_ai(l));
    for l in ai_lines.iter().chain(mine.iter()) {
        s.push_str(&format!("- [ ] {}\n", render(l)));
    }
    Some(s)
}

/// True when the line carries the `#ai` LANE marker. Delimited deliberately: a bare
/// `contains("#ai")` also matches `#aid`, the same trap notes-cockpit.sh:1367 documents.
fn is_ai(line: &str) -> bool {
    line.split_whitespace()
        .any(|w| w.trim_end_matches(',') == "#ai")
}

/// A wave line as the board shows it: checkbox and `#ai` stripped (the lane is already in
/// the `@ai` prefix and the section header), HTML comments dropped. Keeps the text the
/// human typed, so a board row is greppable back to its sheet.
fn render(line: &str) -> String {
    let body = md::task_key(line);
    let body = body
        .split_whitespace()
        .filter(|w| *w != "#ai")
        .collect::<Vec<_>>()
        .join(" ");
    if is_ai(line) {
        format!("@ai {body}")
    } else {
        body
    }
}

/// Render + write the board across every configured profile. Returns its path.
///
/// A profile that fails to resolve is skipped rather than fatal: this runs from
/// `notes today`, and one broken profile must not stop the note being written — the same
/// rule `focus::list_all` follows for the cockpit.
pub fn write(log: &Logger) -> Result<Option<PathBuf>> {
    let active = config::resolve(None)?;
    let Some(path) = board_path(&active) else {
        return Ok(None);
    };

    let today = Local::now().date_naive().format("%Y-%m-%d");
    let mut s = format!(
        "---\nid: board\ntags: [board, projects]\n---\n\n# Board — {today}\n\n\
         _Every project's current `## Wave`, agent lane first. Generated by `notes board` \
         (and each `notes today`) from the same sheets the cockpit reads — edit a task on \
         its project sheet or in the cockpit, never here._\n\n"
    );

    let mut blocks = 0;
    for name in config::all_profile_names()? {
        let Ok(p) = config::resolve(Some(&name)) else {
            continue;
        };
        let dirs = daily::discover_project_dirs(&p);
        if dirs.is_empty() {
            continue;
        }
        let mut profile_blocks: Vec<String> = Vec::new();
        for (proj, summary) in &dirs {
            let Some(dir) = summary.parent() else { continue };
            if let Some(b) = project_block(proj, dir) {
                profile_blocks.push(b);
            }
        }
        if profile_blocks.is_empty() {
            continue;
        }
        // The profile is the grouping the human already thinks in (personal vs bnb vs a
        // job), and it is what `notes --profile X ptask` needs to act on a row.
        s.push_str(&format!("# {name}\n\n"));
        for b in profile_blocks {
            blocks += 1;
            s.push_str(&b);
            s.push('\n');
        }
    }

    if blocks == 0 {
        s.push_str("_(no project has a task sheet yet)_\n");
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating board dir {}", parent.display()))?;
    }
    md::write_atomic(&path, &s).with_context(|| format!("writing {}", path.display()))?;
    log.info("board", &format!("wrote {blocks} project(s) to {}", path.display()));
    Ok(Some(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ai_lane_marker_is_delimited() {
        assert!(is_ai("- [ ] do the thing #ai"));
        assert!(is_ai("- [ ] #ai leading"));
        // The trap notes-cockpit.sh:1367 documents: a substring match also fires on `#aid`.
        assert!(!is_ai("- [ ] first #aid kit"));
        assert!(!is_ai("- [ ] plain task"));
        assert!(!is_ai("- [ ] mentions ai but no tag"));
    }

    #[test]
    fn render_strips_the_checkbox_and_the_tag_but_keeps_the_words() {
        assert_eq!(
            render("- [ ] agentctl roles #ai (0d) <!-- since:2026-08-05 -->"),
            "@ai agentctl roles"
        );
        assert_eq!(render("- [ ] plain one"), "plain one");
        // A non-ai row must not gain the prefix — that would mislabel the human's own work
        // as agent work on the one surface built to tell them apart.
        assert!(!render("- [ ] mine").starts_with("@ai"));
    }

    #[test]
    fn a_project_block_counts_open_and_ai_and_puts_the_agent_lane_first() {
        let dir = std::env::temp_dir().join(format!("notes-board-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("README.md"),
            "# demo\nVersion: v0.3.0\n\n## Wave: v0.3.0 (current)\n\
             - [ ] human task\n- [ ] agent task #ai\n- [x] done one #ai\n",
        )
        .unwrap();

        let b = project_block("demo", &dir).unwrap();
        // the checked item counts for neither total
        assert!(b.contains("## demo · v0.3.0 — 2 open (1 @ai)"), "{b}");
        // agent lane first, regardless of sheet order
        let ai_at = b.find("@ai agent task").unwrap();
        let human_at = b.find("human task").unwrap();
        assert!(ai_at < human_at, "agent lane must sort first:\n{b}");
        assert!(!b.contains("done one"), "checked items are not open:\n{b}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_empty_wave_still_renders_the_project() {
        let dir = std::env::temp_dir().join(format!("notes-board-e-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        // A sheet whose only row is the scaffold placeholder is EMPTY, not one item.
        std::fs::write(
            dir.join("README.md"),
            "# quiet\nVersion: v0.1.0\n\n## Wave: v0.1.0 (current)\n- [ ] \n",
        )
        .unwrap();

        let b = project_block("quiet", &dir).unwrap();
        // Dropping the project entirely would read as "not set up" rather than "idle".
        assert!(b.contains("## quiet · v0.1.0 — 0 open"), "{b}");
        assert!(b.contains("nothing queued"), "{b}");
        assert!(!b.contains("(0 @ai)"), "no lane count when there is none:\n{b}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_dir_with_no_sheet_is_skipped_not_rendered_empty() {
        let dir = std::env::temp_dir().join(format!("notes-board-n-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("summary.md"), "# prose only, no wave\n").unwrap();
        assert!(project_block("nosheet", &dir).is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }
}

/// `notes board` — regenerate, then print the path so the caller can open it.
pub fn run(log: &Logger) -> Result<i32> {
    match write(log)? {
        Some(p) => {
            println!("{}", p.display());
            Ok(0)
        }
        None => {
            eprintln!("no `projects` dir configured for this profile — nothing to board");
            Ok(1)
        }
    }
}
