//! `notes board` — every project's current wave, human and `#ai` lanes, in one file.
//!
//! WHY THIS IS A FILE AND NOT A SECTION
//!
//! The daily note is the human's FOCUS surface. Rendering the board into it was the
//! obvious move and is the wrong one: the note is what gets opened in nvim every morning,
//! and anything pasted above `## Focus` competes with the one list the human actually
//! maintains. `## Current Projects` already proved that — a static index copy that earned
//! its removal. So the board is a file the footer LINKS: visible in one click, never in
//! the way.
//!
//! WHY IT CANNOT DISAGREE WITH THE COCKPIT
//!
//! It reads each project's `## Wave` through `project_tasks::open_wave_for_dir` — the same
//! sheet, the same heading resolution and the same open-task predicate that `notes ptask
//! list` and `notes-cockpit.sh` use. There is one list, rendered twice, rather than two
//! lists that drift. `#ai` is the lane marker throughout (a `/wave` dispatches exactly the
//! `#ai` items), so the board shows the split rather than inventing a vocabulary.
//!
//! CROSS-PROFILE ON PURPOSE
//!
//! Every profile's projects land in one file. "I don't know where <that app> is" was a
//! real complaint: per-profile surfaces mean the work you are not currently looking at is
//! invisible, which is the failure mode a board exists to prevent.

use crate::config::{self, Profile};
use crate::daily;
use crate::logging::Logger;
use crate::md;
use crate::project_tasks;
use anyhow::{Context, Result};
use chrono::Local;
use std::fs;
use std::path::PathBuf;

/// Where the board is written for a profile: alongside the project index it complements
/// (`lab/projects/board.md`). `None` when the profile configures no projects dir, which is
/// also what makes this a no-op on a profile that has no lab.
pub fn board_path(p: &Profile) -> Option<PathBuf> {
    p.project_index
        .as_ref()
        .and_then(|idx| idx.parent())
        .map(|dir| dir.join("board.md"))
}

/// One project's rendered block, or `None` when it has no task sheet.
fn project_block(name: &str, dir: &std::path::Path) -> Option<String> {
    let (version, open) = project_tasks::open_wave_for_dir(dir)?;
    let ai = open.iter().filter(|l| is_ai(l)).count();

    let mut s = format!("## {name} · {version} — {} open", open.len());
    if ai > 0 {
        s.push_str(&format!(" ({ai} @ai)"));
    }
    s.push('\n');
    if open.is_empty() {
        // An empty board is a fact worth rendering. Omitting the project entirely would
        // read as "not set up" rather than "nothing queued".
        s.push_str("_(nothing queued)_\n");
        return Some(s);
    }
    // `#ai` first: the agent lane is the half the human is not holding in their head.
    let (ai_lines, mine): (Vec<_>, Vec<_>) = open.iter().partition(|l| is_ai(l));
    for l in ai_lines.iter().chain(mine.iter()) {
        s.push_str(&format!("- [ ] {}\n", render(l)));
    }
    Some(s)
}

/// True when the line carries the `#ai` LANE marker. Delimited deliberately: a bare
/// `contains("#ai")` also matches `#aid`, the same trap notes-cockpit.sh:1367 documents.
fn is_ai(line: &str) -> bool {
    line.split_whitespace()
        .any(|w| w.trim_end_matches(',') == "#ai")
}

/// A wave line as the board shows it: checkbox and `#ai` stripped (the lane is already in
/// the `@ai` prefix and the section header), HTML comments dropped. Keeps the text the
/// human typed, so a board row is greppable back to its sheet.
fn render(line: &str) -> String {
    let body = md::task_key(line);
    let body = body
        .split_whitespace()
        .filter(|w| *w != "#ai")
        .collect::<Vec<_>>()
        .join(" ");
    if is_ai(line) {
        format!("@ai {body}")
    } else {
        body
    }
}

/// Render + write the board across every configured profile. Returns its path.
///
/// A profile that fails to resolve is skipped rather than fatal: this runs from
/// `notes today`, and one broken profile must not stop the note being written — the same
/// rule `focus::list_all` follows for the cockpit.
pub fn write(log: &Logger) -> Result<Option<PathBuf>> {
    let active = config::resolve(None)?;
    let Some(path) = board_path(&active) else {
        return Ok(None);
    };

    let today = Local::now().date_naive().format("%Y-%m-%d");
    let mut s = format!(
        "---\nid: board\ntags: [board, projects]\n---\n\n# Board — {today}\n\n\
         _Every project's current `## Wave`, agent lane first. Generated by `notes board` \
         (and each `notes today`) from the same sheets the cockpit reads — edit a task on \
         its project sheet or in the cockpit, never here._\n\n"
    );

    let mut blocks = 0;
    for name in config::all_profile_names()? {
        let Ok(p) = config::resolve(Some(&name)) else {
            continue;
        };
        let dirs = daily::discover_project_dirs(&p);
        if dirs.is_empty() {
            continue;
        }
        let mut profile_blocks: Vec<String> = Vec::new();
        for (proj, summary) in &dirs {
            let Some(dir) = summary.parent() else { continue };
            if let Some(b) = project_block(proj, dir) {
                profile_blocks.push(b);
            }
        }
        if profile_blocks.is_empty() {
            continue;
        }
        // The profile is the grouping the human already thinks in (personal vs bnb vs a
        // job), and it is what `notes --profile X ptask` needs to act on a row.
        s.push_str(&format!("# {name}\n\n"));
        for b in profile_blocks {
            blocks += 1;
            s.push_str(&b);
            s.push('\n');
        }
    }

    if blocks == 0 {
        s.push_str("_(no project has a task sheet yet)_\n");
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating board dir {}", parent.display()))?;
    }
    md::write_atomic(&path, &s).with_context(|| format!("writing {}", path.display()))?;
    log.info("board", &format!("wrote {blocks} project(s) to {}", path.display()));
    Ok(Some(path))
}

/// `notes board --ai [--project N]...` — print the agent lane as `<project>\t<text>`.
///
/// The READ side of the board, for the session preflight. It exists because the board was
/// the human's channel to the agent and had ZERO automated readers: 41 open items, 21 of
/// them `#ai`, and nothing at turn 1 looked at any of them. Meanwhile the one channel the
/// preflight did read was an empty placeholder in every project. The human wrote where
/// nothing read; the agent read where nothing wrote.
///
/// Three properties this must hold, all of them because a hook calls it at turn 1:
///
/// 1. NEVER writes. `run` regenerates board.md; this does not touch it. A preflight that
///    rewrites the human's board as a side effect of being asked a question is a
///    surprise, and it would fight `notes today` for the file.
/// 2. ALWAYS exits 0. No projects, no matches, no sheets, no `projects` dir configured --
///    all are ordinary answers meaning "nothing queued". Only a hard I/O error is an
///    error, and even then the caller guards with `|| true`.
/// 3. Reuses `open_wave_for_dir` + `is_ai` + `render`, so it cannot drift from what
///    `board.md` shows. A fourth `#ai` parser is exactly what `is_ai`'s `#aid` trap is
///    about; this adds none.
///
/// An empty `projects` filter means every project, so a caller that cannot resolve the
/// join still gets the whole lane rather than silence.
pub fn print_ai(projects: &[String]) -> Result<i32> {
    let wanted: Vec<String> = projects.iter().map(|p| p.to_lowercase()).collect();

    for name in config::all_profile_names()? {
        let Ok(p) = config::resolve(Some(&name)) else {
            continue;
        };
        for (proj, summary) in daily::discover_project_dirs(&p) {
            if !wanted.is_empty() && !wanted.contains(&proj.to_lowercase()) {
                continue;
            }
            let Some(dir) = summary.parent() else { continue };
            for row in ai_rows_for_dir(&proj, dir) {
                println!("{row}");
            }
        }
    }
    Ok(0)
}

/// The per-project half of `print_ai`, split out so it is testable without a configured
/// profile tree. Returns `<project>\t<text>` rows for the `#ai` lane of the current wave.
fn ai_rows_for_dir(proj: &str, dir: &std::path::Path) -> Vec<String> {
    let Some((_version, open)) = project_tasks::open_wave_for_dir(dir) else {
        return Vec::new();
    };
    open.iter()
        .filter(|l| is_ai(l))
        .map(|line| {
            // `render` prefixes `@ai`, which is redundant once the caller has asked for
            // only the ai lane and is joining on a tab.
            let text = render(line);
            let text = text.strip_prefix("@ai ").unwrap_or(&text).to_string();
            format!("{proj}\t{text}")
        })
        .collect()
}

/// `notes board` — regenerate, then print the path so the caller can open it.
pub fn run(log: &Logger) -> Result<i32> {
    match write(log)? {
        Some(p) => {
            println!("{}", p.display());
            Ok(0)
        }
        None => {
            eprintln!("no `projects` dir configured for this profile — nothing to board");
            Ok(1)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ai_lane_marker_is_delimited() {
        assert!(is_ai("- [ ] do the thing #ai"));
        assert!(is_ai("- [ ] #ai leading"));
        // The trap notes-cockpit.sh:1367 documents: a substring match also fires on `#aid`.
        assert!(!is_ai("- [ ] first #aid kit"));
        assert!(!is_ai("- [ ] plain task"));
        assert!(!is_ai("- [ ] mentions ai but no tag"));
    }

    #[test]
    fn render_strips_the_checkbox_and_the_tag_but_keeps_the_words() {
        assert_eq!(
            render("- [ ] agentctl roles #ai (0d) <!-- since:2026-08-05 -->"),
            "@ai agentctl roles"
        );
        assert_eq!(render("- [ ] plain one"), "plain one");
        // A non-ai row must not gain the prefix — that would mislabel the human's own work
        // as agent work on the one surface built to tell them apart.
        assert!(!render("- [ ] mine").starts_with("@ai"));
    }

    #[test]
    fn a_project_block_counts_open_and_ai_and_puts_the_agent_lane_first() {
        let dir = std::env::temp_dir().join(format!("notes-board-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("README.md"),
            "# demo\nVersion: v0.3.0\n\n## Wave: v0.3.0 (current)\n\
             - [ ] human task\n- [ ] agent task #ai\n- [x] done one #ai\n",
        )
        .unwrap();

        let b = project_block("demo", &dir).unwrap();
        // the checked item counts for neither total
        assert!(b.contains("## demo · v0.3.0 — 2 open (1 @ai)"), "{b}");
        // agent lane first, regardless of sheet order
        let ai_at = b.find("@ai agent task").unwrap();
        let human_at = b.find("human task").unwrap();
        assert!(ai_at < human_at, "agent lane must sort first:\n{b}");
        assert!(!b.contains("done one"), "checked items are not open:\n{b}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_empty_wave_still_renders_the_project() {
        let dir = std::env::temp_dir().join(format!("notes-board-e-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        // A sheet whose only row is the scaffold placeholder is EMPTY, not one item.
        std::fs::write(
            dir.join("README.md"),
            "# quiet\nVersion: v0.1.0\n\n## Wave: v0.1.0 (current)\n- [ ] \n",
        )
        .unwrap();

        let b = project_block("quiet", &dir).unwrap();
        // Dropping the project entirely would read as "not set up" rather than "idle".
        assert!(b.contains("## quiet · v0.1.0 — 0 open"), "{b}");
        assert!(b.contains("nothing queued"), "{b}");
        assert!(!b.contains("(0 @ai)"), "no lane count when there is none:\n{b}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// `sheet <name>` -> a temp project dir holding that README body.
    fn sheet(name: &str, body: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "notes-board-{name}-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("README.md"), body).unwrap();
        dir
    }

    #[test]
    fn ai_rows_emit_project_tab_text_for_the_agent_lane_only() {
        let dir = sheet(
            "airows",
            "# demo\nVersion: v0.3.0\n\n## Wave: v0.3.0 (current)\n\
             - [ ] human task\n- [ ] agent task #ai\n- [x] done one #ai\n",
        );
        let rows = ai_rows_for_dir("demo", &dir);
        // Exactly the ai lane: not the human's row, not the checked one.
        assert_eq!(rows, vec!["demo\tagent task".to_string()], "{rows:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ai_rows_do_not_re_prefix_the_at_ai_marker() {
        // The board renders `@ai <text>` because it mixes both lanes in one list. This
        // path is already ai-only and tab-joined, so a repeated marker is just noise the
        // consumer would have to strip.
        let dir = sheet(
            "noprefix",
            "# d\nVersion: v1\n\n## Wave: v1 (current)\n- [ ] a thing #ai\n",
        );
        let rows = ai_rows_for_dir("d", &dir);
        assert_eq!(rows, vec!["d\ta thing".to_string()]);
        assert!(!rows[0].contains("@ai"), "{rows:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ai_rows_still_exclude_the_aid_substring_trap() {
        // The SAME trap `is_ai` guards, asserted on this path too: it is a new consumer of
        // the lane rule, and the failure would be a first-aid task silently claimed as
        // agent work at turn 1.
        let dir = sheet(
            "aidtrap",
            "# d\nVersion: v1\n\n## Wave: v1 (current)\n\
             - [ ] restock the first #aid kit\n- [ ] real one #ai\n",
        );
        let rows = ai_rows_for_dir("d", &dir);
        assert_eq!(rows, vec!["d\treal one".to_string()], "{rows:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ai_rows_are_empty_for_a_project_with_no_agent_work() {
        // Empty is a valid answer, and must be empty rather than absent-or-error: the
        // preflight prints nothing and moves on.
        let dir = sheet(
            "quiet",
            "# d\nVersion: v1\n\n## Wave: v1 (current)\n- [ ] only mine\n",
        );
        assert!(ai_rows_for_dir("d", &dir).is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ai_rows_are_empty_for_a_dir_with_no_sheet_at_all() {
        let dir = sheet("nosheet", "# prose only\n");
        std::fs::remove_file(dir.join("README.md")).unwrap();
        std::fs::write(dir.join("summary.md"), "# prose only, no wave\n").unwrap();
        assert!(ai_rows_for_dir("d", &dir).is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_dir_with_no_sheet_is_skipped_not_rendered_empty() {
        let dir = std::env::temp_dir().join(format!("notes-board-n-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("summary.md"), "# prose only, no wave\n").unwrap();
        assert!(project_block("nosheet", &dir).is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
