//! `notes index` — scan `[[wikilinks]]` across permanent notes, then report or
//! rebuild the backlink + Map-of-Content (MOC) index. The `scan` is shared with
//! `doctor` for dead-link / orphan detection.

use crate::config::Profile;
use crate::logging::Logger;
use anyhow::Result;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

pub struct Note {
    pub stem: String,
    #[allow(dead_code)] // surfaced by future graph/promotion features
    pub path: PathBuf,
    pub tags: Vec<String>,
    /// outbound link targets (normalised stems)
    #[allow(dead_code)]
    pub links: Vec<String>,
}

pub struct Scan {
    pub notes: Vec<Note>,
    /// stem -> list of note stems that link to it
    pub backlinks: BTreeMap<String, Vec<String>>,
    /// (source_stem, missing_target) pairs
    pub dead: Vec<(String, String)>,
    /// stems with no inbound links
    pub orphans: Vec<String>,
}

/// Collect markdown files (non-recursive) under `dir`.
fn collect(dir: &Path) -> Result<Vec<(String, PathBuf, String)>> {
    let mut out = Vec::new();
    if !dir.exists() {
        return Ok(out);
    }
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) == Some("md") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                let content = fs::read_to_string(&path).unwrap_or_default();
                out.push((stem.to_lowercase(), path, content));
            }
        }
    }
    Ok(out)
}

/// Extract `[[target]]` link stems from content (handles `path/name`, `name|alias`, `name#anchor`).
pub fn extract_links(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = content.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'[' && bytes[i + 1] == b'[' {
            if let Some(end) = content[i + 2..].find("]]") {
                let inner = &content[i + 2..i + 2 + end];
                let target = inner
                    .split('|')
                    .next()
                    .unwrap_or(inner)
                    .split('#')
                    .next()
                    .unwrap_or(inner);
                let stem = target.rsplit('/').next().unwrap_or(target).trim();
                let stem = stem.strip_suffix(".md").unwrap_or(stem);
                if !stem.is_empty() {
                    out.push(stem.to_lowercase());
                }
                i = i + 2 + end + 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

pub(crate) fn extract_tags(content: &str) -> Vec<String> {
    // crude frontmatter `tags: [a, b]` reader
    for line in content.lines().take(15) {
        let t = line.trim();
        if let Some(rest) = t.strip_prefix("tags:") {
            let rest = rest.trim().trim_start_matches('[').trim_end_matches(']');
            return rest
                .split(',')
                .map(|s| s.trim().trim_matches('"').to_string())
                .filter(|s| !s.is_empty())
                .collect();
        }
    }
    Vec::new()
}

pub fn scan(p: &Profile) -> Result<Scan> {
    let raw = collect(&p.zettel)?;
    let known: std::collections::HashSet<String> = raw.iter().map(|(s, _, _)| s.clone()).collect();

    let mut notes = Vec::new();
    let mut backlinks: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut dead = Vec::new();

    for (stem, path, content) in &raw {
        let links = extract_links(content);
        for target in &links {
            if known.contains(target) {
                backlinks
                    .entry(target.clone())
                    .or_default()
                    .push(stem.clone());
            } else {
                dead.push((stem.clone(), target.clone()));
            }
        }
        notes.push(Note {
            stem: stem.clone(),
            path: path.clone(),
            tags: extract_tags(content),
            links,
        });
    }

    let orphans: Vec<String> = notes
        .iter()
        .filter(|n| !backlinks.contains_key(&n.stem))
        .map(|n| n.stem.clone())
        .collect();

    Ok(Scan {
        notes,
        backlinks,
        dead,
        orphans,
    })
}

pub fn run(p: &Profile, log: &Logger, rebuild: bool) -> Result<()> {
    let s = scan(p)?;
    println!(
        "permanent notes: {}  links resolved: {}  dead: {}  orphans: {}",
        s.notes.len(),
        s.backlinks.values().map(|v| v.len()).sum::<usize>(),
        s.dead.len(),
        s.orphans.len()
    );

    if !rebuild {
        return Ok(());
    }

    fs::create_dir_all(&p.index)?;

    // backlinks.md
    let mut bl = String::from("# Backlinks\n\n_Generated by `notes index --rebuild`._\n\n");
    for (target, sources) in &s.backlinks {
        bl.push_str(&format!("## [[{target}]]\n"));
        for src in sources {
            bl.push_str(&format!("- [[{src}]]\n"));
        }
        bl.push('\n');
    }
    fs::write(p.index.join("backlinks.md"), bl)?;

    // moc.md — notes grouped by tag
    let mut by_tag: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for n in &s.notes {
        if n.tags.is_empty() {
            by_tag
                .entry("untagged".to_string())
                .or_default()
                .push(n.stem.clone());
        } else {
            for tag in &n.tags {
                by_tag.entry(tag.clone()).or_default().push(n.stem.clone());
            }
        }
    }
    let mut moc = String::from("# Map of Content\n\n_Generated by `notes index --rebuild`._\n\n");
    for (tag, stems) in &by_tag {
        moc.push_str(&format!("## #{tag}\n"));
        for stem in stems {
            moc.push_str(&format!("- [[{stem}]]\n"));
        }
        moc.push('\n');
    }
    fs::write(p.index.join("moc.md"), moc)?;

    log.info(
        "index",
        &format!(
            "rebuilt index ({} notes) at {}",
            s.notes.len(),
            p.index.display()
        ),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn link_extraction() {
        let c = "see [[foo]] and [[bar/baz|Baz]] and [[qux#section]] and [[x.md]]";
        let links = extract_links(c);
        assert_eq!(links, vec!["foo", "baz", "qux", "x"]);
    }

    #[test]
    fn tag_extraction() {
        let c = "---\ntags: [idea, \"rust\"]\n---\n# t";
        assert_eq!(extract_tags(c), vec!["idea", "rust"]);
    }
}
