#!/usr/bin/env bash
# regen-anchor.sh — regenerate ONLY the <!-- AUTO:START -->…<!-- AUTO:END --> block of a
# project anchor at ~/.agent/anchors/{project}.md from the filesystem. Hand-curated
# sections above the marker are never touched. Scaffolds a fresh anchor if none exists.
#
#   regen-anchor.sh [project]           # project defaults to name resolved from $PWD
#   regen-anchor.sh [project] --rotate  # also age old decisions out to a sidecar
#
# Deterministic + idempotent: same inputs → same AUTO block. No network.
#
# WIRED TO A STOP HOOK (stop-post.d/87-regen-anchor.sh). Before that it was wired to
# NOTHING -- its only caller was a skill a human had to invoke by hand, and the result
# was an AUTO block two months stale: the dotfiles anchor advertised its latest eval as
# 2026-06-08 while the directory held 2026-08-09. Nothing failed, because a stale
# generated block and a fresh one look identical. That matters more now that the session
# preflight stopped listing plans and lessons itself and delegates both to this block.
set -euo pipefail

HOOKS_DIR="$HOME/.dotfiles/.config/shared-hooks"
# project_map_file() from project-name.sh owns the path. It is defined there rather than
# here because five files each defined it and one was wrong (see its comment). Fall back
# only if the resolver is not on this machine yet.
if [ -r "$HOME/.config/shared-hooks/project-name.sh" ]; then
  # shellcheck source=/dev/null
  . "$HOME/.config/shared-hooks/project-name.sh"
fi
if declare -F project_map_file >/dev/null 2>&1; then
  MAP_FILE="$(project_map_file)"
else
  MAP_FILE="${PROJECT_MAP_FILE:-$HOME/.config/shared-hooks/project-map.json}"
fi

# The shared AUTO-block splicer. Hard-sourced (not guarded), same as
# regen-project-index.sh: this script's whole job is that splice, and the inline awk it
# replaces lacked the `cmp -s` guard -- so an unguarded fallback would silently restore
# the unconditional write that makes this hook dirty ~/.agent on every single Stop.
MD_SPLICE_LIB="$HOME/.local/lib/md-splice.sh"
if [ ! -r "$MD_SPLICE_LIB" ]; then
  echo "ERROR: $MD_SPLICE_LIB not found — is the dotfiles stow current?" >&2
  exit 1
fi
# shellcheck source=/dev/null
. "$MD_SPLICE_LIB"

# --- resolve project name + flags ---
ROTATE=0
ARGS=()
for a in "$@"; do
  case "$a" in
    --rotate) ROTATE=1 ;;
    *) ARGS+=("$a") ;;
  esac
done
set -- ${ARGS+"${ARGS[@]}"}

if [ "${1:-}" != "" ]; then
  PROJECT="$1"
else
  # shellcheck disable=SC1091
  . "$HOOKS_DIR/project-name.sh"
  PROJECT="$(resolve_project_name "${CLAUDE_PROJECT_DIR:-$PWD}")"
fi

ANCHOR_DIR="$HOME/.agent/anchors"
ANCHOR="$ANCHOR_DIR/$PROJECT.md"
PLAN_DIR="$HOME/.agent/plans/$PROJECT"
LESSONS="$HOME/.agent/lessons/$PROJECT.md"
EVAL_DIR="$HOME/.agent/evals/$PROJECT"
mkdir -p "$ANCHOR_DIR"

START='<!-- AUTO:START — regenerated by /project-index; edits below are overwritten -->'
END='<!-- AUTO:END -->'

# --- gather facts ---
# repo path. `project_repo_path` rather than a bare `.paths` reverse-lookup, because a
# project need not BE a repo: an app in a monorepo, or a product whose sessions register
# under the tool repo they ran in, reaches its checkout only via `trackers.<n>.repo`. The
# bare lookup this replaces returned empty for exactly those projects, so their anchors
# rendered no Repo line at all.
REPO=""
if declare -F project_repo_path >/dev/null 2>&1; then
  REPO="$(project_repo_path "$PROJECT")"
elif command -v jq >/dev/null 2>&1 && [ -f "$MAP_FILE" ]; then
  REPO=$(jq -r --arg n "$PROJECT" '.paths | to_entries[] | select(.value==$n) | .key' "$MAP_FILE" 2>/dev/null | head -1)
fi
# tracker line
TRACKER=""
if command -v jq >/dev/null 2>&1 && [ -f "$MAP_FILE" ]; then
  TRACKER=$(jq -r --arg n "$PROJECT" '(.trackers[$n] // .trackers.default) | "\(.system) — \(.instance)"' "$MAP_FILE" 2>/dev/null)
fi
# latest eval
LATEST_EVAL=$(ls -t "$EVAL_DIR" 2>/dev/null | head -1 || true)
# lab ideation dir (best-effort: same name under ANY bus root). There is more than one:
# the personal lab, the BNB lab (lab/bnb — BNB is ours, so it roots under lab/ rather than
# employment/), and a root per client job. lab-roots.sh owns that list; hard-coding the
# personal root here reported "(no dedicated entry)" for every project under another one.
# lab-roots.sh ships in the PRIVATE overlay, so it is colocated with the hooks only at the
# stowed path — not inside ~/.dotfiles. Check both, same as session-preflight.sh.
for LAB_ROOTS_LIB in "$HOOKS_DIR/lab-roots.sh" "$HOME/.config/shared-hooks/lab-roots.sh"; do
  if [ -r "$LAB_ROOTS_LIB" ]; then
    # shellcheck source=/dev/null
    . "$LAB_ROOTS_LIB"
    break
  fi
done
if declare -F lab_roots >/dev/null 2>&1; then
  LAB_ROOT_LIST=$(lab_roots 2>/dev/null || true)
else
  LAB_ROOT_LIST="$HOME/.notes/lab/projects/current"
fi
# The lab directory name IS the project name -- project-map.json is the sole registry
# and project-map-doctor enforces that every lab dir has an entry, so there is nothing
# to search for. The loop this replaces also tried `${PROJECT%-agent}` and
# `${PROJECT%-platform}`, which silently attached a project's anchor to whatever
# directory happened to look similar.
#
# Searched under EVERY name that belongs to this repo, not just the project's own. The
# two namespaces are deliberately different: a session in ~/.dotfiles resolves to
# `dotfiles`, while the human files its lab work under `notes-cockpit` and
# `agent-runtime`. Matching on the project name alone found nothing for exactly the
# projects that have the most lab material, and reported "(no dedicated entry)" -- which
# reads as "nothing here" rather than "looked under the wrong name".
LAB_DIR=""
LAB_NAMES="$PROJECT"
if declare -F project_lab_names >/dev/null 2>&1; then
  LAB_NAMES="$(project_lab_names "$PROJECT")"
  [ -n "$LAB_NAMES" ] || LAB_NAMES="$PROJECT"
fi
while IFS= read -r lab_root; do
  [ -n "$lab_root" ] || continue
  while IFS= read -r lab_name; do
    [ -n "$lab_name" ] || continue
    if [ -d "$lab_root/$lab_name" ]; then
      LAB_DIR="${LAB_DIR:+$LAB_DIR, }\`${lab_root/#$HOME/\~}/$lab_name/\`"
    fi
  done <<< "$LAB_NAMES"
done <<< "$LAB_ROOT_LIST"
[ -z "$LAB_DIR" ] && LAB_DIR='`~/.notes/lab/` (no dedicated projects/current entry)'
# repo docs
REPO_DOCS="_(none)_"
[ -n "$REPO" ] && [ -d "$REPO/docs" ] && REPO_DOCS="$REPO/docs/"

# --- build the AUTO block ---
auto_block() {
  echo "$START"
  echo "## Links"
  echo "- Plans:   \`~/.agent/plans/$PROJECT/\`"
  echo "- Lessons: \`~/.agent/lessons/$PROJECT.md\`"
  if [ -n "$LATEST_EVAL" ]; then
    echo "- Evals:   \`~/.agent/evals/$PROJECT/\` (latest: \`$LATEST_EVAL\`)"
  else
    echo "- Evals:   \`~/.agent/evals/$PROJECT/\`"
  fi
  echo "- Ideation/docs: $LAB_DIR"
  echo "- Repo docs: $REPO_DOCS"
  [ -n "$REPO" ] && echo "- Repo: \`$REPO\`"
  [ -n "$TRACKER" ] && echo "- Tracker: $TRACKER"
  echo
  echo "## Active plans (most recent)"
  if [ -d "$PLAN_DIR" ]; then
    local plans
    plans=$(ls -t "$PLAN_DIR" 2>/dev/null | grep -vxE 'active|archive|_archive|tasks' | head -5 || true)
    if [ -n "$plans" ]; then
      echo "$plans" | sed 's/^/- `/; s/$/`/'
    else
      echo "- _(no plans yet)_"
    fi
  else
    echo "- _(no plans dir yet)_"
  fi
  echo
  echo "## Recent lessons (digest)"
  if [ -f "$LESSONS" ]; then
    local digest
    # tail of bullet lessons, each truncated to keep the digest scannable (it's injected
    # at session start — one mega-lesson must not dominate the context window)
    digest=$(grep -E '^- ' "$LESSONS" 2>/dev/null | tail -5 \
      | awk '{ if (length($0) > 200) print substr($0,1,197) "…"; else print }' || true)
    if [ -n "$digest" ]; then
      echo "$digest"
    else
      echo "- _(lessons file has no bullet entries yet)_"
    fi
  else
    echo "- _(no lessons file yet)_"
  fi
  echo "$END"
}

# --- scaffold if missing ---
if [ ! -f "$ANCHOR" ]; then
  {
    echo "# $PROJECT — anchor"
    echo
    echo "## Key URLs & facts"
    [ -n "$REPO" ] && echo "- **Repo:** \`$REPO\`"
    [ -n "$TRACKER" ] && echo "- **Tracker:** $TRACKER"
    echo "- _(fill in: main branch, deploy target, key paths)_"
    echo
    echo "## Decisions log"
    echo "- _(record decisions + WHY as they land — the irreplaceable part)_"
    echo
    echo "## Blockers / known issues"
    echo "- _(none yet)_"
    echo
    auto_block
  } > "$ANCHOR"
  echo "scaffolded new anchor: $ANCHOR"
  exit 0
fi

# --- replace only the AUTO block in the existing file ---
if ! grep -qF 'AUTO:START' "$ANCHOR"; then
  echo "ERROR: $ANCHOR has no AUTO:START marker — append one or delete the file to re-scaffold." >&2
  exit 1
fi

if md_splice "$ANCHOR" 'AUTO:START' 'AUTO:END' auto_block; then
  if [ "$MD_SPLICE_CHANGED" = "1" ]; then
    echo "regenerated AUTO block: $ANCHOR"
  else
    # The no-op path is why this can run on every Stop. Without it, a hook that fires
    # each turn would rewrite the file each turn, and ~/.agent -- which is a git repo
    # with a 15-minute auto-commit -- would carry a meaningless anchor commit per turn.
    echo "AUTO block unchanged: $ANCHOR"
  fi
else
  echo "ERROR: could not splice $ANCHOR" >&2
  exit 1
fi

# --- rotate the decisions log (opt-in) ---
#
# anchor-lib.sh caps what the PREFLIGHT injects, which protects the reader but not the
# file: the log is append-only and newest-first, so it grows without bound and every
# consumer that reads it whole keeps paying. Rotation moves the aged tail into a sidecar
# and leaves a link, so nothing is lost and the anchor stays a front door.
#
# Opt-in, never automatic: this REWRITES a hand-curated section, and the Stop hook must
# not do that behind a human's back. The hook calls this script without --rotate.
if [ "$ROTATE" = "1" ]; then
  KEEP="${ANCHOR_ROTATE_KEEP:-8}"
  SIDECAR="$ANCHOR_DIR/$PROJECT.decisions.md"
  # Entry boundaries are top-level dated bullets, the same grammar anchor-lib.sh reads.
  # Counted INSIDE the log section only: an anchor can carry dated bullets elsewhere
  # (the dotfiles one has entries stranded below AUTO:END), and counting those would
  # rotate a log that has not actually grown.
  TOTAL=$(awk '/^## Decisions log/{f=1;next} f&&/^## /{f=0} f&&/^- \*\*/{n++} END{print n+0}' "$ANCHOR")
  if [ "$TOTAL" -gt "$KEEP" ]; then
    ROT_TMP="$(mktemp)"; SIDE_TMP="$(mktemp)"
    # Displayed ~-relative: the anchor is read by humans and models on more than one
    # machine, and a hard-coded /home/<user> path reads as machine-specific state.
    awk -v keep="$KEEP" -v side="$SIDE_TMP" -v link="${SIDECAR/#$HOME/\~}" '
      /^## Decisions log/ { print; inlog = 1; n = 0; next }
      inlog && /^## / { if (n > keep) emit_link(); inlog = 0; print; next }
      # Drop any link a previous rotation left, so repeated rotations do not stack them.
      inlog && /^_\(older entries rotated to/ { next }
      inlog {
        if ($0 ~ /^- \*\*/) n++
        if (n > keep) { print > side; next }
        print
        next
      }
      { print }
      END { if (inlog && n > keep) emit_link() }
      function emit_link() {
        print ""
        printf "_(older entries rotated to `%s`)_\n", link
        print ""
      }
    ' "$ANCHOR" > "$ROT_TMP"

    if [ -s "$SIDE_TMP" ]; then
      # Prepend, not append: the sidecar is newest-first too, so a later rotation's
      # entries are newer than everything already in it.
      { echo "# $PROJECT — decisions log (rotated out of the anchor)"
        echo
        cat "$SIDE_TMP"
        [ -f "$SIDECAR" ] && sed '1{/^# /d}' "$SIDECAR"
      } > "$SIDECAR.new"
      mv "$SIDECAR.new" "$SIDECAR"
      mv "$ROT_TMP" "$ANCHOR"
      echo "rotated $((TOTAL - KEEP)) decisions to: $SIDECAR"
    else
      rm -f "$ROT_TMP"
    fi
    rm -f "$SIDE_TMP"
  fi
fi
