### RULES ###

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = match:float false, match:workspace w[tv1], border_size 0
# windowrule = match:float false, match:workspace w[tv1], rounding 0
# windowrule = match:float false, match:workspace f[1], border_size 0
# windowrule = match:float false, match:workspace f[1], rounding 0

windowrule = match:class ^(kitty)$, workspace 1
windowrule = match:class ^(firefox)$, workspace 2
windowrule = match:class ^(obsidian)$, workspace 6

# Unity - keep Hub out of the editor workspace
windowrule = match:class ^(unityhub)$, workspace 8
windowrule = match:class ^(Unity)$, match:float false, workspace 3, group set

# Android/Testing tools
windowrule = match:class ^(scrcpy)$, workspace 6, group barred
windowrule = match:class ^(chromium|Chromium|chrome|Chrome|google-chrome|Google-chrome)$, match:title :.*Playwright.*, workspace 5, no_initial_focus true, suppress_event activate
windowrule = match:class ^(firefox-default)$, workspace 5, no_initial_focus true, suppress_event activate
windowrule = match:class ^([Ee]mulator(64)?(-arm)?|qemu-system)$, workspace 5, no_initial_focus true, suppress_event activate
