#!/usr/bin/env bats
# regen-anchor.sh + stop-post.d/87-regen-anchor.sh.
#
# The generator existed for two months with NO caller, so its AUTO block went stale and
# nothing said so -- a stale generated block and a fresh one render identically. These
# tests pin the two properties that make wiring it to every Stop safe:
#
#   the block actually refreshes            (else the hook is decoration)
#   an unchanged block is NOT rewritten     (else ~/.agent, a git repo with a 15-minute
#                                            auto-commit, gains a commit every turn)
#
# and the two that keep the hook from doing damage: it never scaffolds an anchor for a
# directory nobody asked about, and it never rotates behind a human's back.

setup() {
  load '../vendor/bats-support/load'
  load '../vendor/bats-assert/load'
  load '../helpers/sandbox'
  sandbox_init basic

  REGEN="$REPO_ROOT/.claude/skills/memory/project-index/regen-anchor.sh"
  HOOK="$REPO_ROOT/.claude/hooks/stop-post.d/87-regen-anchor.sh"

  # The script reads its libs from the STOWED path, which sandbox_init has rewritten.
  # md-splice.sh is already linked in there by sandbox_init; only project-name.sh needs
  # placing.
  mkdir -p "$HOME/.config/shared-hooks" "$HOME/.agent/anchors" \
           "$HOME/.agent/plans/proj" "$HOME/.agent/evals/proj" "$HOME/.agent/lessons"
  cp "$REPO_ROOT/.config/shared-hooks/project-name.sh" "$HOME/.config/shared-hooks/"

  MAP="$HOME/project-map.json"
  export PROJECT_MAP_FILE="$MAP"
  cat > "$MAP" <<'EOF'
{
  "paths": { "/repos/toolrepo": "toolrepo" },
  "apps": {},
  "aliases": {},
  "trackers": {
    "_comment_lab_projects": "a string value, to catch an unguarded jq",
    "proj": { "system": "vikunja", "instance": "https://example.test" }
  }
}
EOF

  ANCHOR="$HOME/.agent/anchors/proj.md"
}

seed_anchor() {
  local entries="${1:-3}" i
  {
    echo "# proj - anchor"
    echo
    echo "## Key URLs & facts"
    echo "- a hand-written fact"
    echo
    echo "## Decisions log"
    for i in $(seq "$entries" -1 1); do
      echo "- **2026-08-0$i:** decision $i"
      echo "  a continuation line for $i"
    done
    echo
    echo "## Blockers / known issues"
    echo "- none"
    echo
    echo "<!-- AUTO:START — regenerated by /project-index; edits below are overwritten -->"
    echo "## Links"
    echo "- Evals:   \`~/.agent/evals/proj/\` (latest: \`1999-01-01.md\`)"
    echo "<!-- AUTO:END -->"
  } > "$ANCHOR"
}

# ── the generator ────────────────────────────────────────────────────────────

@test "regen-anchor: refreshes a stale AUTO block" {
  seed_anchor
  touch "$HOME/.agent/evals/proj/2026-08-10.md"
  run bash "$REGEN" proj
  assert_success
  assert_output --partial 'regenerated AUTO block'
  run cat "$ANCHOR"
  assert_output --partial '2026-08-10.md'
  refute_output --partial '1999-01-01.md'
}

@test "regen-anchor: preserves the hand-curated sections byte-for-byte" {
  seed_anchor
  local before
  before=$(awk '/^## Key URLs/,/^<!-- AUTO:START/' "$ANCHOR" | head -n -1)
  bash "$REGEN" proj >/dev/null
  local after
  after=$(awk '/^## Key URLs/,/^<!-- AUTO:START/' "$ANCHOR" | head -n -1)
  assert_equal "$after" "$before"
}

@test "regen-anchor: a second run does NOT rewrite the file" {
  # The cmp guard. Without it every Stop dirties ~/.agent.
  seed_anchor
  bash "$REGEN" proj >/dev/null
  local mtime_before
  mtime_before=$(stat -c %Y "$ANCHOR")
  sleep 1.1

  run bash "$REGEN" proj
  assert_success
  assert_output --partial 'AUTO block unchanged'
  assert_equal "$(stat -c %Y "$ANCHOR")" "$mtime_before"
}

@test "regen-anchor: errors rather than guessing when the marker is absent" {
  printf '# proj\n\n## Key URLs & facts\n- a fact\n' > "$ANCHOR"
  run bash "$REGEN" proj
  assert_failure
  assert_output --partial 'no AUTO:START marker'
}

# ── --rotate ─────────────────────────────────────────────────────────────────

@test "regen-anchor --rotate: ages the tail into a sidecar and leaves a link" {
  seed_anchor 6
  ANCHOR_ROTATE_KEEP=2 run bash "$REGEN" proj --rotate
  assert_success
  assert_output --partial 'rotated 4 decisions'

  run cat "$ANCHOR"
  assert_output --partial 'decision 6'
  assert_output --partial 'decision 5'
  refute_output --partial 'decision 1'
  assert_output --partial 'older entries rotated to'

  run cat "$HOME/.agent/anchors/proj.decisions.md"
  assert_output --partial 'decision 1'
  assert_output --partial 'a continuation line for 1'
}

@test "regen-anchor --rotate: repeated rotation does not stack link lines" {
  seed_anchor 6
  ANCHOR_ROTATE_KEEP=2 bash "$REGEN" proj --rotate >/dev/null
  ANCHOR_ROTATE_KEEP=2 bash "$REGEN" proj --rotate >/dev/null
  run grep -c 'older entries rotated to' "$ANCHOR"
  assert_output '1'
}

@test "regen-anchor: rotation NEVER happens without the flag" {
  # The hook runs without it, and rotation rewrites a hand-curated section.
  seed_anchor 6
  ANCHOR_ROTATE_KEEP=2 run bash "$REGEN" proj
  assert_success
  run cat "$ANCHOR"
  assert_output --partial 'decision 1'
  refute_output --partial 'older entries rotated to'
  [ ! -f "$HOME/.agent/anchors/proj.decisions.md" ]
}

# ── the stop hook ────────────────────────────────────────────────────────────

@test "87-regen-anchor: refreshes the anchor for the session's project" {
  seed_anchor
  touch "$HOME/.agent/evals/proj/2026-08-10.md"
  # The DEPLOYED path, which is what the hook reads. ~/.claude/skills stays flat
  # however the repo is organised, and that stability is the point of it.
  mkdir -p "$HOME/.claude/skills/project-index"
  cp "$REGEN" "$HOME/.claude/skills/project-index/"
  mkdir -p "$HOME/proj"

  cat > "$MAP" <<EOF
{ "paths": { "$HOME/proj": "proj" }, "apps": {}, "aliases": {}, "trackers": {} }
EOF

  CLAUDE_PROJECT_DIR="$HOME/proj" run bash "$HOOK" </dev/null
  assert_success
  run cat "$ANCHOR"
  assert_output --partial '2026-08-10.md'
}

@test "87-regen-anchor: NEVER scaffolds an anchor for a project that has none" {
  # A Stop hook that mints project files for every directory anyone opens is how
  # ~/.agent filled with namespaces nobody reads.
  mkdir -p "$HOME/.claude/skills/project-index" "$HOME/stranger"
  cp "$REGEN" "$HOME/.claude/skills/project-index/"

  CLAUDE_PROJECT_DIR="$HOME/stranger" run bash "$HOOK" </dev/null
  assert_success
  [ ! -f "$HOME/.agent/anchors/stranger.md" ]
}

@test "87-regen-anchor: exits 0 when the generator is missing" {
  # Never block a Stop.
  seed_anchor
  CLAUDE_PROJECT_DIR="$HOME/proj" run bash "$HOOK" </dev/null
  assert_success
}
