#!/bin/bash
# Color palette — GENERATED by theme-switch from palettes/jackie-brown.sh
# Do not edit by hand; run: theme-switch jackie-brown --only sketchybar
# Format is 0xAARRGGBB — 0xff = fully opaque, 0xcc ≈ 80%, 0x66 ≈ 40%

# Bar background
export BAR_COLOR=0xe62c1c15
export BAR_BORDER_COLOR=0x4dae8c20
# Meeting-state signals: fixed red/green/yellow, theme-INDEPENDENT on purpose. These are
# semantic alerts (unjoined / in-call / attended-then-left), not decoration — a pastel
# theme must not turn the "join now" pulse blue. meeting_watch.sh drives the whole bar.
export BAR_ALERT_COLOR=0xe6ef5734
export BAR_INCALL_COLOR=0xe686a83e
export BAR_MAYBE_COLOR=0xe6ff9f1c
export BAR_LEFT_COLOR=0xe6ffcc2f

# Item backgrounds
export ITEM_BG_COLOR=0x663d2a1f
export ACCENT_BG_COLOR=0x33ae8c20
export ACTIVE_BG_COLOR=0x4dffcc2f

# Foreground / accents
export WHITE=0xffbfbfbf
export DIM=0xff666666
export GOLD=0xffffcc2f
export GREEN=0xff86a83e
export RED=0xffef5734
export BLUE=0xff246db2
export CYAN=0xff00acee
export MAGENTA=0xffcf5ec0
export YELLOW=0xffbdbe00

# Semantic
export CLOCK_COLOR=$GOLD
export BATTERY_COLOR=$GREEN
export BATTERY_LOW_COLOR=$RED
export VOLUME_COLOR=$MAGENTA
export CPU_COLOR=$BLUE
export CALENDAR_COLOR=$CYAN
R_COLOR=$CYAN
