#!/bin/bash
# Color palette — GENERATED by theme-switch from palettes/ayaka.sh
# Do not edit by hand; run: theme-switch ayaka --only sketchybar
# Format is 0xAARRGGBB — 0xff = fully opaque, 0xcc ≈ 80%, 0x66 ≈ 40%

# Bar background
export BAR_COLOR=0xe636283d
export BAR_BORDER_COLOR=0x4d9098a4
# Meeting-state signals: fixed red/green/yellow, theme-INDEPENDENT on purpose. These are
# semantic alerts (unjoined / in-call / attended-then-left), not decoration — a pastel
# theme must not turn the "join now" pulse blue. meeting_watch.sh drives the whole bar.
export BAR_ALERT_COLOR=0xe6ef5734
export BAR_INCALL_COLOR=0xe686a83e
export BAR_LEFT_COLOR=0xe6ffcc2f

# Item backgrounds
export ITEM_BG_COLOR=0x66473351
export ACCENT_BG_COLOR=0x339098a4
export ACTIVE_BG_COLOR=0x4dcedaeb

# Foreground / accents
export WHITE=0xffcedaeb
export DIM=0xff9098a4
export GOLD=0xffcedaeb
export GREEN=0xffab8cae
export RED=0xff71ade9
export BLUE=0xff9ea0d3
export CYAN=0xffe1b4ce
export MAGENTA=0xff8bb8e9
export YELLOW=0xffe59db1

# Semantic
export CLOCK_COLOR=$GOLD
export BATTERY_COLOR=$GREEN
export BATTERY_LOW_COLOR=$RED
export VOLUME_COLOR=$MAGENTA
export CPU_COLOR=$BLUE
export CALENDAR_COLOR=$CYAN
