#!/usr/bin/env bats
# anchor-lib.sh trims the single largest thing injected at turn 1: the anchor is 78%
# of the SessionStart context, and `## Decisions log` is most of the anchor.
#
# The risk in trimming is not that it trims too little -- it is that it silently eats
# a section that is load-bearing in full. So the assertions here are mostly about what
# must SURVIVE: every other section, byte-for-byte, including the generated AUTO block
# that carries plans and lessons (which the preflight stops printing separately and
# starts trusting this to pass through).
#
# The truncation is newest-first-dependent. If the log is ever reordered oldest-first,
# `keeps the NEWEST entries` fails, which is the correct alarm.

setup() {
  load '../vendor/bats-support/load'
  load '../vendor/bats-assert/load'
  load '../helpers/sandbox'
  sandbox_init basic
  source "$REPO_ROOT/.config/shared-hooks/anchor-lib.sh"
  ANCHOR="$BATS_TEST_TMPDIR/proj.md"
}

# seed_anchor <n-entries> — a realistic anchor: sections around a NEWEST-FIRST log of
# <n> dated entries, each 3 lines, plus an AUTO block below it.
seed_anchor() {
  local n="${1:-12}" i day
  {
    echo "# proj - anchor"
    echo
    echo "## Key URLs & facts"
    echo "- **Repo:** \`~/proj\`"
    echo "- **Main branch:** \`main\`"
    echo
    echo "## Decisions log"
    for i in $(seq "$n" -1 1); do
      day=$(printf '%02d' "$i")
      echo "- **2026-08-$day:** decision number $i headline"
      echo "  a continuation line for entry $i"
      echo "  a second continuation line for entry $i"
    done
    echo
    echo "## Blockers / known issues"
    echo "- a blocker that must survive"
    echo
    echo "<!-- AUTO:START — regenerated by /project-index; edits below are overwritten -->"
    echo "## Links"
    echo "- Evals: ~/.agent/evals/proj/ (latest: 2026-08-09.md)"
    echo
    echo "## Active plans (most recent)"
    echo "- a plan the preflight no longer prints itself"
    echo
    echo "## Recent lessons (digest)"
    echo "- a lesson the preflight no longer prints itself"
    echo "<!-- AUTO:END -->"
  } > "$ANCHOR"
}

# ── what must survive ────────────────────────────────────────────────────────

@test "anchor_inject: every section other than the log passes through" {
  seed_anchor 12
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_output --partial '## Key URLs & facts'
  assert_output --partial '- **Repo:** `~/proj`'
  assert_output --partial '## Blockers / known issues'
  assert_output --partial '- a blocker that must survive'
}

@test "anchor_inject: the generated AUTO block passes through byte-for-byte" {
  # The preflight stops printing plans and lessons itself and trusts this block for
  # both. If the trim ate it, turn 1 would lose them with no error.
  seed_anchor 12
  local expected
  expected=$(sed -n '/AUTO:START/,/AUTO:END/p' "$ANCHOR")
  run anchor_inject "$ANCHOR" 6
  assert_success
  local got
  got=$(anchor_inject "$ANCHOR" 6 | sed -n '/AUTO:START/,/AUTO:END/p')
  assert_equal "$got" "$expected"
}

# ── the trim itself ──────────────────────────────────────────────────────────

@test "anchor_inject: keeps the NEWEST entries and drops the oldest" {
  # 12 entries, 3 lines each; a 6-line budget rounds up to 2 whole entries.
  seed_anchor 12
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_output --partial 'decision number 12 headline'
  assert_output --partial 'decision number 11 headline'
  refute_output --partial 'decision number 1 headline'
  refute_output --partial 'decision number 5 headline'
}

@test "anchor_inject: a kept entry keeps its continuation lines" {
  # Cutting mid-entry reads as a corrupted file, not a shortened one.
  seed_anchor 12
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_output --partial 'a continuation line for entry 12'
  assert_output --partial 'a second continuation line for entry 12'
}

@test "anchor_inject: the pointer counts the omitted entries and names the file" {
  seed_anchor 12
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_output --partial "_(10 older entries omitted - read $ANCHOR)_"
}

@test "anchor_inject: the pointer is singular for exactly one omitted entry" {
  seed_anchor 3
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_output --partial '_(1 older entry omitted'
}

@test "anchor_inject: a log that fits gets NO pointer" {
  # The negative control for the pointer: a short anchor must be untouched.
  seed_anchor 2
  run anchor_inject "$ANCHOR" 100
  assert_success
  refute_output --partial 'older entr'
  assert_equal "$(anchor_inject "$ANCHOR" 100)" "$(cat "$ANCHOR")"
}

@test "anchor_inject: an entry longer than the whole budget is still emitted whole" {
  # The budget is a floor, not a ceiling. Emitting a log with no entries in it would
  # be worse than overshooting.
  seed_anchor 12
  run anchor_inject "$ANCHOR" 1
  assert_success
  assert_output --partial 'decision number 12 headline'
  assert_output --partial 'a second continuation line for entry 12'
  assert_output --partial '_(11 older entries omitted'
}

@test "anchor_inject: an anchor with no decisions log passes through unchanged" {
  printf '# proj\n\n## Key URLs & facts\n- a fact\n\n## Blockers\n- none\n' > "$ANCHOR"
  run anchor_inject "$ANCHOR" 6
  assert_success
  assert_equal "$(anchor_inject "$ANCHOR" 6)" "$(cat "$ANCHOR")"
}

@test "anchor_inject: a log that runs to end-of-file still gets its pointer" {
  # No trailing section to trigger the section-close path -- the END rule must.
  {
    echo "# proj"
    echo "## Decisions log"
    local i
    for i in 9 8 7 6 5 4 3 2 1; do
      echo "- **2026-08-0$i:** entry $i"
      echo "  continuation $i"
    done
  } > "$ANCHOR"
  run anchor_inject "$ANCHOR" 2
  assert_success
  assert_output --partial 'entry 9'
  refute_output --partial 'entry 1
'
  assert_output --partial 'older entries omitted'
}

@test "anchor_inject: a missing anchor prints nothing and succeeds" {
  run anchor_inject "$BATS_TEST_TMPDIR/nope.md"
  assert_success
  assert_output ''
}
